spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/socket_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root

  cache:
    synchronize: true # 判断开启哪种缓存,为true 开启ehcache缓存 false 开启redis缓存
    type: ehcache
#    type: redis
#  profiles:
#    active: redis

  redis:
      port: 6379
      database: 0
      host: 172.19.34.19
      password:
      jedis:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
      timeout: 5000ms
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp

mybatis:
  mapper-locations: classpath*:mapper/*.xml

