spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/socket_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root

  cache:
    synchronize: true # 判断开启哪种缓存,为true 开启ehcache缓存 false 开启redis缓存
    type: ehcache
#    type: redis
#  profiles:
#    active: redis

  redis:
      port: 6379
      database: 0
      host: 172.19.34.19
      password:
      jedis:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
      timeout: 5000ms
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp

logging:
  config: classpath:log4j2.xml

mybatis:
  mapper-locations: classpath*:mapper/*.xml

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.story.storyadmin.domain.entity
  mapperClassScan: com.story.storyadmin.mapper
  global-config:
    db-config:
      id-type: auto
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    #    logic-delete-value: 0
    #    logic-not-delete-value: 1
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
    logic-delete-value: 1
    logic-not-delete-value: 0
    #    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    #sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

token:
  #  token过期时间，单位分钟
  tokenExpireTime: 120
  #  RefreshToken过期时间，单位：分钟, 24*60=1440
  refreshTokenExpireTime: 1440
  #  shiro缓存有效期，单位分钟,2*60=120
  shiroCacheExpireTime: 120
  #  token加密密钥
  secretKey: storywebkey
#动态设置拦截器
permission-config:
  perms:
    - key: /
      value: anon
    - key: /user/login
      value: anon
    - key: /logout
      value: logout
    - key: /**
      value: jwt

